[versions]
exposed = "0.61.0"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-migration = { module = "org.jetbrains.exposed:exposed-migration", version.ref = "exposed"}
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed"}